# Generated by Django 3.1.4 on 2020-12-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeiros_passos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='anoPublicacao',
            new_name='ano_publicacao',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='emailEditora',
            new_name='email_editora',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='numerpPaginas',
            new_name='numero_paginas',
        ),
    ]
